[package]
name = "wincleaner"
version = "0.1.0"
edition = "2021"

[dependencies]
freya = "0.3.4"
tokio = { version = "1.0", features = ["full"] }
chrono = "0.4"
once_cell = "1.19"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"